### ISSUE TITLE
Bundle is way too big on prod build

### ISSUE THREAD

**Issue by PollRobots** [PollRobots/scheme#2]
I'm assuming that monaco is being brought in rather than being pulled from the CDN. Obviously this is bad.

**Comment by jaredkrinke** [comment]
FYI: I recently embedded Monaco via a CDN and wrote down how to do it (for some reason the official docs seem to have deleted some of the samples I used):

https://log.schemescape.com/posts/web-development/embedding-monaco-from-cdn.html
