### ISSUE TITLE
Strange `if` behavior in a function

### ISSUE THREAD

**Issue by samdphillips** [PollRobots/scheme#3]
This doesn't work
```scheme
> (define (y x) (if (= 1 x) 'y 'n))
> (y 1)
y
> (y 0)
y
```

This works though
```scheme
> (define a 0)
> (if (= 1 a) 'y 'n)
n
> (set! a 1)
> (if (= 1 a) 'y 'n)
y
```

**Comment by PollRobots** [comment]
hmmm, in your `(define (y x) ...` then x is bound to the list of arguments to the lambda, at which point `(= 1 x)` will be evaluated as `(= 1 (1))` which is returning an error (it should be throwing it, this is a ubiquitous bug, see issue #4 

If you define as below, it works as expected

``` scheme
(define (y (x)) (if (= 1 x) 'y 'n))
```

**Comment by PollRobots** [comment]
and error objects are truthy, so your definition always takes the 'then' path

**Comment by samdphillips** [comment]
I see.  In Scheme `(define (f a b c) body)` expands to `(define f (lambda (a b c) body))`.

If you intend on it not working this way you should document it or a lot of other Scheme users will probably report similar bugs.

**Comment by PollRobots** [comment]
Oops, yeah, just checked the spec, I'll fix it
