### ISSUE TITLE
call/cc give error

### ISSUE THREAD

**Issue by jcubic** [PollRobots/scheme#5]
This is an example that helped me find an error in BiwaScheme and its call/cc implementation biwascheme/biwascheme#257. Here is the code. You can use it to test your implementation:

```scheme
(call/cc (lambda (return)
           (let ((n 5)
                 (result (list))
                 (k #f))
             (set! result (append result (list (call/cc (lambda (return)
                                                          (set! k return)
                                                          "Hello")))))
             (when #t
               (if (zero? n)
                   (return result))
               (set! n (- n 1))
               (k (string-append "Hello <" (number->string n) ">"))))))
```

It should return:

```
("Hello <0>")
```

All elements are implemented but git weird:

> `<error args 4>`

**Comment by PollRobots** [comment]
Thanks for reporting this!

There's (apparantly) a bug in `number->string`, if I change your code to

``` scheme
(call/cc (lambda (return)
           (let ((n 5)
                 (result (list))
                 (k #f))
             (set! result (append result (list (call/cc (lambda (return)
                                                          (set! k return)
                                                          "Hello")))))
             (when #t
               (if (zero? n)
                   (return result))
               (set! n (- n 1))
               (k (string-append "Hello <" (number->string n 10) ">"))))))
```

Then it works as expected

**Comment by jcubic** [comment]
Nice, awesome project. You should also try to test [quasiquote](https://github.com/jcubic/lips/blob/master/tests/quotation.scm) and [syntax-rules](https://github.com/jcubic/lips/blob/master/tests/syntax.scm).

**Comment by jcubic** [comment]
If you want to run the code from unit tests without Ava and by helper code, you will need to write mocks for Ava testing framework, I think that you only need those:

* `to.throw` macro
* `test` function that executes the second argument, and can print the message before execution.
* `t.is` macro the check for equality and print the expression when not equal. With ava in my Scheme, it's a JavaScript method on `t` object.
